version: 2
updates:
  # Monitor GitHub Actions with global grouping
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "test"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: "Australia/Melbourne"
    groups:
      all-actions:
        patterns:
          - "*"

  # Monitor Docker base image
  - package-ecosystem: "docker"
    directory: "sigenergy-modbus-simulator"
    target-branch: "test"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: "Australia/Melbourne"
